# Generated by Django 4.2.5 on 2023-10-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=models.CharField(default='799999999', max_length=20),
        ),
    ]
