# Generated by Django 4.2.5 on 2023-10-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_author_validate_for_phonenambers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='validate_for_phonenambers',
        ),
        migrations.AddField(
            model_name='author',
            name='validate_for_phonenumbers',
            field=models.BooleanField(default=False),
        ),
    ]
