# Generated by Django 4.2.5 on 2023-10-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_author_amount_reception'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='79999999999', max_length=20, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
