# Generated by Django 4.2.5 on 2023-10-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_author_reason_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='reason_request',
        ),
        migrations.AddField(
            model_name='author',
            name='num',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
