# Generated by Django 4.2.5 on 2023-10-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_remove_author_reason_request_author_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='num',
        ),
        migrations.AddField(
            model_name='author',
            name='reason_request',
            field=models.CharField(default='Через ";"', max_length=200),
        ),
    ]
