# Generated by Django 4.2.5 on 2023-10-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_remove_author_num_author_reason_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='reason_request',
            field=models.CharField(default='Через ";"', max_length=200, null=True),
        ),
    ]
