# Generated by Django 4.2.5 on 2023-10-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_alter_author_reason_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='reason_request',
            field=models.CharField(default='Через ";"', max_length=200),
        ),
    ]
