# Generated by Django 4.2.6 on 2023-10-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_alter_author_reason_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='view_lesson',
            field=models.BooleanField(default=False),
        ),
    ]
