# Generated by Django 4.2.6 on 2023-10-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_order_date_order_view_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='view_lesson',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
