# Generated by Django 4.2.6 on 2023-10-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0016_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(default='2', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(default='1', max_length=400, null=True),
        ),
    ]
