# Generated by Django 4.2.6 on 2023-10-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0017_alter_order_date_alter_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(default='none.n@mail.ru', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='name_client',
            field=models.CharField(default='ФИО', max_length=90, null=True),
        ),
    ]
