# Generated by Django 4.2.6 on 2023-10-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0019_alter_order_view_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='view_lesson',
            field=models.BooleanField(default=True),
        ),
    ]
